"""Telegram interface — thin adapter over core logic.

Handler extraction (src.interfaces.telegram.handlers) is planned for v2.2.5.
Until then, handlers live in src.bot.app and are re-exported from here.
"""
# patch_deep_scan: bug1_handlers_reexport
from src.bot.app import (  # noqa: F401
    start_handler,
    help_handler,
    status_handler,
    memory_handler,
    pinmemory_handler,
    unpinmemory_handler,
    deletememory_handler,
    watch_handler,
    watchers_handler,
    stopwatch_handler,
    wakelog_handler,
    providers_handler,
    reload_handler,
    files_handler,
    cleanworkspace_handler,
    cmdhistory_handler,
    broadcast_handler,
    delete_me_handler,
    addkey_handler,
    key_submission_handler,
    photo_handler,
    document_handler,
    callback_query_handler,
    stop_task_handler,
    stop_command_handler,
    autowatch_handler,
)

__all__ = [
    "start_handler",
    "help_handler",
    "status_handler",
    "memory_handler",
    "pinmemory_handler",
    "unpinmemory_handler",
    "deletememory_handler",
    "watch_handler",
    "watchers_handler",
    "stopwatch_handler",
    "wakelog_handler",
    "providers_handler",
    "reload_handler",
    "files_handler",
    "cleanworkspace_handler",
    "cmdhistory_handler",
    "broadcast_handler",
    "delete_me_handler",
    "addkey_handler",
    "key_submission_handler",
    "photo_handler",
    "document_handler",
    "callback_query_handler",
    "stop_task_handler",
    "stop_command_handler",
    "autowatch_handler",
]
