#!/usr/bin/env bash
# rika-agent setup wizard — interactive, multi-platform
set -euo pipefail

R="\033[0;31m" G="\033[0;32m" Y="\033[0;33m" B="\033[0;34m"
C="\033[0;36m" W="\033[1;37m" D="\033[2m" NC="\033[0m"
OK="${G}✓${NC}" ERR="${R}✗${NC}" WARN="${Y}!${NC}" NFO="${C}→${NC}"

say()  { echo -e "  $*"; }
ok()   { echo -e "  ${OK} $*"; }
err()  { echo -e "  ${ERR} ${R}$*${NC}"; }
warn() { echo -e "  ${WARN} ${Y}$*${NC}"; }
info() { echo -e "  ${NFO} ${D}$*${NC}"; }
hr()   { echo -e "  ${D}──────────────────────────────────────${NC}"; }
ask()  { echo -en "  ${B}?${NC} $1 "; }

header() { echo ""; echo -e "  ${W}$*${NC}"; hr; }

check_cmd()   { command -v "$1" &>/dev/null; }
require_cmd() {
    if ! check_cmd "$1"; then
        err "$1 is required but not installed."
        exit 1
    fi
}

clear
echo ""
echo -e "  ${C}╔═════════════════════════════════════╗${NC}"
echo -e "  ${C}║         rika-agent   setup           ║${NC}"
echo -e "  ${C}╚═════════════════════════════════════╝${NC}"
echo ""

# ── Requirements ──────────────────────────────────────────────────────────────
header "Checking requirements"
require_cmd python3

PY=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
MAJ=$(echo "$PY" | cut -d. -f1); MIN=$(echo "$PY" | cut -d. -f2)
[[ "$MAJ" -lt 3 || ( "$MAJ" -eq 3 && "$MIN" -lt 12 ) ]] && { err "Python 3.12+ required. Got $PY"; exit 1; }
ok "Python $PY"
check_cmd git && ok "git" || warn "git not found (optional)"
DOCKER_OK=false
check_cmd docker && docker info &>/dev/null 2>&1 && DOCKER_OK=true \
    && ok "Docker (available for sandbox level 2)" \
    || info "Docker not found or not running"

# ── Virtualenv ─────────────────────────────────────────────────────────────────
header "Python environment"
if [ ! -d ".venv" ]; then
    info "Creating .venv..."
    python3 -m venv .venv && ok "Created .venv"
else
    ok ".venv already exists"
fi
source .venv/bin/activate
info "Installing dependencies..."
pip install --quiet --upgrade pip 2>/dev/null
pip install --quiet -r requirements.txt 2>/dev/null
ok "Dependencies installed"

# ── Platform selection ─────────────────────────────────────────────────────────
header "Platform selection"
say "rika-agent supports multiple interfaces simultaneously."
say "Select the ones you want to enable:"
echo ""

declare -a ENABLED_PLATFORMS=()

ask "Enable Telegram bot? (requires @BotFather token) [Y/n]:"; read -r TG_EN
if [[ ! "$TG_EN" =~ ^[Nn]$ ]]; then
    ENABLED_PLATFORMS+=("telegram")
    ok "Telegram interface selected"
else
    info "Telegram interface disabled"
fi

ask "Enable REST API server? (Flask, POST /api/chat) [y/N]:"; read -r API_EN
if [[ "$API_EN" =~ ^[Yy]$ ]]; then
    ENABLED_PLATFORMS+=("api")
    ok "API interface selected"
else
    info "API interface disabled"
fi

ask "Enable Discord bot? (requires Discord Developer app token) [y/N]:"; read -r DS_EN
if [[ "$DS_EN" =~ ^[Yy]$ ]]; then
    ENABLED_PLATFORMS+=("discord")
    ok "Discord interface selected"
    info "Remember to enable Message Content Intent in Discord Developer Portal"
else
    info "Discord interface disabled"
fi

if [ ${#ENABLED_PLATFORMS[@]} -eq 0 ]; then
    warn "No interface selected. The agent will run in headless mode (background tasks only)."
    say "You can enable interfaces later by editing .env\n"
fi

# ── .env ──────────────────────────────────────────────────────────────────────
header "Configuration — .env"
SKIP_ENV=0
if [ -f ".env" ]; then
    warn ".env already exists."
    ask "Reconfigure it? [y/N]"; read -r RE
    [[ "$RE" =~ ^[Yy]$ ]] || SKIP_ENV=1
fi

if [ "$SKIP_ENV" -eq 0 ]; then
    ENC_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
    {
        echo "# rika-agent .env — generated by setup.sh"
        echo "BOT_ENCRYPTION_KEY=\"$ENC_KEY\""
        echo "DATABASE_PATH=./data/rk.db"
    } > .env

    # Telegram config
    if [[ " ${ENABLED_PLATFORMS[*]} " =~ "telegram" ]]; then
        echo ""
        say "Get a bot token from ${C}@BotFather${NC} on Telegram:"
        say "  /newbot → follow prompts → copy the token"
        echo ""
        ask "Telegram bot token:"; read -r BOT_TOKEN
        while [ -z "$BOT_TOKEN" ]; do
            err "Token required for Telegram mode."
            ask "Telegram bot token:"; read -r BOT_TOKEN
        done
        echo "TELEGRAM_BOT_TOKEN=\"$BOT_TOKEN\"" >> .env
        ok "Telegram token saved"

        echo ""
        say "Your Telegram user ID (message ${C}@userinfobot${NC} to find it):"
        ask "Your Telegram ID (required for single-user auth):"; read -r OWNER_ID
        if [ -n "$OWNER_ID" ]; then
            echo "OWNER_USER_ID=\"$OWNER_ID\"" >> .env
        else
            warn "No owner ID set — bot will respond to ALL Telegram users"
        fi
    fi

    # Discord config
    if [[ " ${ENABLED_PLATFORMS[*]} " =~ "discord" ]]; then
        echo ""
        say "Create a bot at ${C}https://discord.com/developers/applications${NC}"
        say "  → New Application → Bot → Reset Token"
        say "  Enable Message Content Intent under Privileged Gateway Intents"
        say "  Invite bot with scope 'bot' and 'Send Messages', 'Read Message History'"
        echo ""
        ask "Discord bot token:"; read -r DS_TOKEN
        while [ -z "$DS_TOKEN" ]; do
            err "Token required for Discord mode."
            ask "Discord bot token:"; read -r DS_TOKEN
        done
        echo "DISCORD_BOT_TOKEN=\"$DS_TOKEN\"" >> .env
        ok "Discord token saved"

        echo ""
        say "Your Discord user ID (18-digit snowflake). Find it: Settings → Advanced → Developer Mode ON → right-click username → Copy User ID"
        ask "Your Discord user ID:"; read -r DS_OWNER
        if [ -n "$DS_OWNER" ] && [ -z "${OWNER_ID:-}" ]; then
            echo "OWNER_USER_ID=\"$DS_OWNER\"" >> .env
            echo "DISCORD_OWNER_ID=\"$DS_OWNER\"" >> .env
            warn "No Telegram OWNER_USER_ID was set — using Discord ID as owner"
        elif [ -n "$DS_OWNER" ]; then
            info "Telegram OWNER_USER_ID already set — Discord will use same owner ID"
        else
            warn "No owner ID set — bot will respond to ALL Discord users"
        fi

        info "Installing discord.py..."
        pip install --quiet discord.py 2>/dev/null || warn "discord.py install failed (run 'pip install discord.py' manually)"
        ok "Discord configured"
    fi

    # API config
    if [[ " ${ENABLED_PLATFORMS[*]} " =~ "api" ]]; then
        echo ""
        ask "API host [0.0.0.0]:"; read -r API_HOST
        echo "API_HOST=\"${API_HOST:-0.0.0.0}\"" >> .env

        ask "API port [5000]:"; read -r API_PORT
        echo "API_PORT=\"${API_PORT:-5000}\"" >> .env

        ask "Enable API debug mode? [y/N]:"; read -r API_DBG
        if [[ "$API_DBG" =~ ^[Yy]$ ]]; then
            echo "API_DEBUG=true" >> .env
        fi
        ok "API server configured: http://${API_HOST:-0.0.0.0}:${API_PORT:-5000}"
    fi

    # Agent name
    echo ""
    say "Give your agent a name (optional — press Enter for default)"
    say "  Examples: rika, aria, rei, cipher, lain"
    ask "Agent name:"; read -r AGENT_NAME
    if [ -n "$AGENT_NAME" ]; then
        echo "AGENT_NAME=\"$AGENT_NAME\"" >> .env
    fi
    echo "LOG_LEVEL=info" >> .env

    # Provider API keys
    echo ""
    header "Provider API keys"
    say "Press Enter to skip any. You can add them later with /addkey."
    say "At least one key is required to use the agent."
    echo ""
    ask "Gemini   (aistudio.google.com):";         read -r GK
    ask "Groq     (console.groq.com):";            read -r GROQK
    ask "OpenRouter (openrouter.ai):";             read -r ORK
    ask "NVIDIA NIM (build.nvidia.com):";          read -r NVIDIAK
    ask "Vercel AI Gateway (vercel.com):";         read -r VERCELK

    [ -n "$GK" ]      && echo "GEMINI_API_KEY=\"$GK\""       >> .env
    [ -n "$GROQK" ]   && echo "GROQ_API_KEY=\"$GROQK\""      >> .env
    [ -n "$ORK" ]     && echo "OPENROUTER_API_KEY=\"$ORK\""  >> .env
    [ -n "$NVIDIAK" ] && echo "NVIDIA_API_KEY=\"$NVIDIAK\""  >> .env
    [ -n "$VERCELK" ] && {
        echo "VERCEL_API_KEY=\"$VERCELK\"" >> .env
        echo "VERCEL=1" >> .env
    }
    ok "Provider keys saved"

    # Postgres (optional)
    echo ""
    header "Optional: Postgres backend"
    say "By default rika uses SQLite. Set a POSTGRES_URL to use Postgres instead."
    say "Required for Vercel / Railway / Render deployments."
    echo ""
    ask "Postgres URL (Enter to skip):"; read -r PGURL
    if [ -n "$PGURL" ]; then
        echo "POSTGRES_URL=\"$PGURL\"" >> .env
        info "Installing asyncpg..."
        pip install --quiet asyncpg 2>/dev/null
        ok "Postgres configured"
    else
        info "Using SQLite (default)"
    fi

    ok ".env created (encryption key auto-generated)"
fi

# ── soul.md ───────────────────────────────────────────────────────────────────
header "Agent identity — soul.md"
if [ ! -f "soul.md" ]; then
    cp soul.md.template soul.md
    ok "soul.md created from template"
    say "Edit ${C}soul.md${NC} to customise the agent's personality."
else
    ok "soul.md exists"
fi

# ── Sandbox level ─────────────────────────────────────────────────────────────
header "Code execution sandbox"
say "Controls how safely the agent runs Python code."
say ""
say "  ${W}Level 0${NC} — RestrictedPython   — in-process, no file/network access"
say "  ${W}Level 1${NC} — Process + ulimit   — real Python, resource-limited   ${G}(recommended)${NC}"
say "  ${W}Level 2${NC} — Docker             — full isolation, max security     ${C}(best if Docker available)${NC}"
echo ""

BEST_LEVEL=0
if $DOCKER_OK; then
    BEST_LEVEL=2
    say "  Docker is available — ${C}Level 2 recommended${NC}"
elif python3 -c "import platform; exit(0 if platform.system() in ('Linux','Darwin') else 1)" 2>/dev/null; then
    BEST_LEVEL=1
    say "  Linux/macOS detected — ${C}Level 1 recommended${NC}"
else
    say "  Windows detected — ${C}Level 0 recommended${NC}"
fi
echo ""
ask "Sandbox level [0/1/2, Enter for $BEST_LEVEL]:"; read -r SB_INPUT
SB_LEVEL="${SB_INPUT:-$BEST_LEVEL}"
[[ "$SB_LEVEL" =~ ^[012]$ ]] || SB_LEVEL="$BEST_LEVEL"

python3 -c "
import json, os
path = 'config.json'
c = json.load(open(path)) if os.path.exists(path) else {}
c['sandbox_level'] = $SB_LEVEL
json.dump(c, open(path, 'w'), indent=2)
print(f'  sandbox_level set to $SB_LEVEL')
"
ok "Sandbox level $SB_LEVEL configured"

if [ "$SB_LEVEL" -eq 2 ] && $DOCKER_OK; then
    info "Pre-pulling Docker image python:3.12-slim..."
    docker pull python:3.12-slim -q && ok "Docker image ready" \
        || warn "Docker pull failed — will pull on first run"
fi

# ── Ollama (optional) ─────────────────────────────────────────────────────────
header "Local LLM — Ollama (optional)"
say "Use local models (llama3, mistral, qwen, etc.) for free."
say "Install from ${C}https://ollama.com${NC} then run: ollama pull llama3.2"
echo ""
ask "Enable Ollama? [y/N]:"; read -r OL_EN
if [[ "$OL_EN" =~ ^[Yy]$ ]]; then
    ask "Ollama URL [http://localhost:11434]:"; read -r OL_URL
    OL_URL="${OL_URL:-http://localhost:11434}"
    ask "Default model [llama3.2]:"; read -r OL_MODEL
    OL_MODEL="${OL_MODEL:-llama3.2}"
    python3 -c "
import json
c = json.load(open('config.json')) if os.path.exists('config.json') else {}
c['ollama_enabled'] = True
c['ollama_base_url'] = '$OL_URL'
c['ollama_default_model'] = '$OL_MODEL'
json.dump(c, open('config.json', 'w'), indent=2)
"
    ok "Ollama enabled: $OL_URL ($OL_MODEL)"
else
    info "Ollama skipped"
fi

# ── G4F (optional) ────────────────────────────────────────────────────────────
header "Free providers — G4F (optional)"
say "G4F provides free access to GPT-4, Claude etc. via reverse-engineered APIs."
warn "G4F is unstable and may break without notice. Use as a last-resort fallback."
echo ""
ask "Install and enable G4F? [y/N]:"; read -r G4F_EN
if [[ "$G4F_EN" =~ ^[Yy]$ ]]; then
    info "Installing g4f..."
    pip install --quiet g4f 2>/dev/null
    python3 -c "
import json
c = json.load(open('config.json')) if os.path.exists('config.json') else {}
c['g4f_enabled'] = True
json.dump(c, open('config.json', 'w'), indent=2)
"
    ok "G4F installed and enabled"
else
    info "G4F skipped"
fi

# ── Database ──────────────────────────────────────────────────────────────────
header "Database"
mkdir -p data
info "Running migrations..."
python3 -m src.db.migrate && ok "Database ready"

# ── Workspace ─────────────────────────────────────────────────────────────────
header "Agent workspace"
WORKSPACE_DEFAULT="$HOME/.rika/shared"
ask "Workspace path [${WORKSPACE_DEFAULT}]:"; read -r WS_INPUT
WORKSPACE="${WS_INPUT:-$WORKSPACE_DEFAULT}"
mkdir -p "$WORKSPACE"
ok "Workspace: $WORKSPACE"

python3 -c "
import json
c = json.load(open('config.json')) if os.path.exists('config.json') else {}
c['workspace_path'] = '$WORKSPACE'
json.dump(c, open('config.json', 'w'), indent=2)
"

# ── Multi-model routing (optional) ────────────────────────────────────────────
header "Multi-model routing (optional)"
say "Route complex tasks to a powerful model and simple tasks to a fast, cheap one."
say "You can also configure this later by editing config.json directly."
echo ""
ask "Configure model tiers now? [y/N]:"; read -r MT_EN
if [[ "$MT_EN" =~ ^[Yy]$ ]]; then
    echo ""
    say "Complex tier: coding, deep analysis.  Examples: anthropic/claude-opus-4-5 (openrouter)"
    ask "  provider [openrouter]:"; read -r CP; CP="${CP:-openrouter}"
    ask "  model [anthropic/claude-opus-4-5]:"; read -r CM; CM="${CM:-anthropic/claude-opus-4-5}"
    echo ""
    say "Mid tier: orchestrator + executor (default for most tasks)."
    ask "  provider [groq]:"; read -r MP; MP="${MP:-groq}"
    ask "  model [llama-3.3-70b-versatile]:"; read -r MM; MM="${MM:-llama-3.3-70b-versatile}"
    echo ""
    say "Low tier: summarisation, translation, formatting."
    ask "  provider [groq]:"; read -r LP; LP="${LP:-groq}"
    ask "  model [llama-3.1-8b-instant]:"; read -r LM; LM="${LM:-llama-3.1-8b-instant}"

    python3 -c "
import json, os
path = 'config.json'
c = json.load(open(path)) if os.path.exists(path) else {}
c['model_tiers'] = {
    'complex': [{'provider': '$CP', 'model': '$CM'}],
    'mid':     [{'provider': '$MP', 'model': '$MM'}],
    'low':     [{'provider': '$LP', 'model': '$LM'}],
}
c['tier_fallback_chain'] = ['complex', 'mid', 'low']
json.dump(c, open(path, 'w'), indent=2)
"
    ok "Model tiers written to config.json"
else
    info "Using defaults — edit config.json to customise later"
fi


# ── Systemd auto-start (optional, Linux only) ────────────────────────────────
header "Systemd service (optional)"
if command -v systemctl &>/dev/null; then
    ask "Install systemd user service to auto-start on boot? [y/N]:"; read -r SD_EN
    if [[ "$SD_EN" =~ ^[Yy]$ ]]; then
        SERVICE_DIR="$HOME/.config/systemd/user"
        mkdir -p "$SERVICE_DIR"
        cat > "$SERVICE_DIR/rika-agent.service" << UNIT
[Unit]
Description=rika-agent AI bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${PROJECT_DIR:-$(pwd)}
ExecStart=/bin/bash ${PROJECT_DIR:-$(pwd)}/scripts/start.sh
Restart=on-failure
RestartSec=10
StandardOutput=append:$HOME/.rika/logs/rika-agent.service.log
StandardError=append:$HOME/.rika/logs/rika-agent.service.log

[Install]
WantedBy=default.target
UNIT
        systemctl --user daemon-reload 2>/dev/null
        systemctl --user enable rika-agent.service 2>/dev/null
        ok "Service installed: $SERVICE_DIR/rika-agent.service"
        say "  Start now:   bash scripts/start.sh"
        say "  Via systemd: systemctl --user start rika-agent"
        say "  Logs:        journalctl --user -u rika-agent -f"
    else
        info "Systemd service skipped"
    fi
else
    info "systemctl not available — skipping service setup"
fi


# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${G}╔══════════════════════════════════════════╗${NC}"
echo -e "  ${G}║            Setup complete!               ║${NC}"
echo -e "  ${G}╚══════════════════════════════════════════╝${NC}"
echo ""

if [[ " ${ENABLED_PLATFORMS[*]} " =~ "telegram" ]] \
    || [[ " ${ENABLED_PLATFORMS[*]} " =~ "discord" ]]; then
    say "Start:"
    say "  ${C}bash scripts/start.sh${NC}"
    echo ""
fi
if [[ " ${ENABLED_PLATFORMS[*]} " =~ "api" ]]; then
    say "Test with curl:"
    say "  ${C}curl -X POST http://localhost:${API_PORT:-5000}/api/chat \\${NC}"
    say "  ${C}  -H 'X-API-Key: my-key' -H 'Content-Type: application/json' \\${NC}"
    say "  ${C}  -d '{\"message\": \"hello\"}'${NC}"
    echo ""
fi

say "With Docker:"
say "  ${C}docker compose up -d${NC}"
echo ""
say "Add more API keys any time:"
say "  ${C}/addkey groq:\"gsk_...\"${NC}"
say "  ${C}/addkey nvidia:\"nvapi-...\"${NC}"
echo ""
